MBS-8586: Simplify horizontal scrolling
mebis-lp/moodle-mod_kanban pull request #34
Opened 2024-01-07 20:28 UTC by sh-csg

2024-01-17 15:08 UTC, PhMemmel requested changes
Looks good in general.

Some minor questions/thoughts/suggestions:
- Would it be a good idea to make the steps when clicking the buttons dependent on the card with? Currently it feels a bit like I have to click too often to move right, so maybe we can use cardwith/2 as scroll length or even 0.9*cardwith or something?
- To fit into the overall design maybe we could style the buttons with rounded corners.
- It would be nice if the buttons could be transparent, so when they are shown, you can still see the content of the card behind them
- User might eventually expect that I can keep scrolling by keeping the buttons pressed. Is this something we want?

2024-01-18 15:32 UTC, sh-csg commented
Introducing transparency produces a quite messy output - maybe we'll find another approach for implementing
this. 
Default scrolling distance is now the width of a column, inner corners are rounded.
Whether to keep scrolling when button is constantly pressed is an open question for me - I would move this to another ticket,

2024-02-01 13:06 UTC, PhMemmel commented on amd/src/board.js
> +        if (main.scrollLeft < main.scrollLeftMax) {
Not a standard property, does not work on Chrome and many other browsers, see: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeftMax?retiredLocale=de

Needs to be changed.

2024-02-01 13:07 UTC, PhMemmel commented on styles.css
> +}
still no newline

2024-02-01 13:07 UTC, PhMemmel requested changes
Pls see comments.

2024-02-01 18:53 UTC, sh-csg commented
Accidentally pushed wrong version - sorry for that!

2024-02-13 10:39 UTC, PhMemmel approved these changes
Great feature, well done!

Internally reviewed, happy to merge.

Some more improvements regarding button styling and general handling will be introduced in a separate PR.

2024-02-13 10:39 UTC, merged